// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvqC5uHtPfwtDHKG0Xi_5GProHy0hjLCk',
    appId: '1:49857206686:web:f5f85f173c5db99b999e8f',
    messagingSenderId: '49857206686',
    projectId: 'toms-2026',
    authDomain: 'toms-2026.firebaseapp.com',
    storageBucket: 'toms-2026.firebasestorage.app',
    measurementId: 'G-TPM0NPM6BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyVAWdCklf1TS2INioUFZ8rvxim1hvEAg',
    appId: '1:49857206686:android:24f34196bcbc6fbb999e8f',
    messagingSenderId: '49857206686',
    projectId: 'toms-2026',
    storageBucket: 'toms-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgm3YN6m3DlNnirNknptG7ZGVsVsk7Jzk',
    appId: '1:49857206686:ios:b666535a25decb76999e8f',
    messagingSenderId: '49857206686',
    projectId: 'toms-2026',
    storageBucket: 'toms-2026.firebasestorage.app',
    iosBundleId: 'com.toms.toms',
  );
}
